version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: safeer/testifyclient:1.00
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testify-client
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}